name: Bug report
description: Report a bug to help us improve
title: "bug: "

body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for taking the time to fill out this bug report!

  - type: input
    id: title
    attributes:
      label: Bug Title
      description: A clear and concise title of what the bug is.
      placeholder: Bug title
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Use the classes '....'
        3. Try running '....'
        4. See error
      description: Steps to reproduce the bug
    validations:
      required: true

  - type: input
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Expected behavior
    validations:
      required: true

  - type: input
    id: actual
    attributes:
      label: Actual behavior
      description: A clear and concise description of what actually happened.
      placeholder: Actual behavior
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is the bug?
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: |
        Provide details about your environment:
        - OS: [e.g. Windows, MacOS, Linux]
        - Roblox-TS Version
        - Typescript Version
      placeholder: Environment details
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Additional context
    validations:
      required: false