blank_issues_enabled: false
contact_links:
  - name: Roblox-TS discord
    url: https://discord.roblox-ts.com//
    about: You can find me in the Roblox-TS discord if you have futher questions/comments.
