name: Feature/Class Support Request
title: "feat: "
description: Make a request for a feature or for certain css class support
body:
  - type: dropdown
    id: type
    attributes:
      label: What type of request is it?
      options:
        - Class Support Request
        - Other Feature Request
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "What would you like to see support added for?"
      value: I would like to see support for [insert here]
    validations:
      required: true
      
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Checks
      options:
        - label: This feature is possible to do when making UI in roblox studio, not just from webdev CSS
          required: true
        - label: I am willing to contribute to this
